Remote Sampling part 1 (Fetching Sampling Rules)
bhautikpip/opentelemetry-go-contrib pull request #987
Opened 2021-11-30 23:31 UTC by bhautikpip

This PR is a part of the remote sampling support. This PR is adding support for fetching sampling rules from X-Ray service via `GetSamplingRules` API using `aws proxy` extension provided by collector. The PR has added necessary functions and interface to achieve this functionality and the scope of this PR is limited to fetching sampling rules. I have added couple ToDos which I will address in next consecutive PRs. I will just give a highlight of next follow ups PR after this. 

1. Fetching Sampling Target via GetSamplingTargets API
2. Business logic for remote sampling
3. Instantiate fixed ration based sampler to address fixed rate requirements
4. Integration testing

2021-12-03 04:04 UTC, Aneurysm9 requested changes

2021-12-03 04:04 UTC, Aneurysm9 commented on samplers/aws/xray/sampling_rule.go
> +	*properties
Why is this embedded?  It doesn't look like `properties` is used independently so shouldn't this either be a named field or the fields of `properties` included here?

2021-12-03 04:04 UTC, Aneurysm9 commented on samplers/aws/xray/sampling_rule.go
> +	attributes    interface{}
What is this type?  `interface{}` is almost certainly wrong.

2021-12-03 04:04 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +		t.Reset()
This shouldn't reset the timer every interval, should it?  Does that invalidate the channel currently being ranged over?

2021-12-06 18:26 UTC, bhautikpip commented on samplers/aws/xray/remote_sampler.go
> +		t.Reset()
I think `Reset` should be invoked only on stopped or expired timers with drained channels. Since here timer would be expiring every interval so we are resetting it. I don't see any other concern here since we have this logic in X-Ray Go SDK as well since a long time. Do you see any other potential concerns here?

2021-12-06 21:25 UTC, Aneurysm9 commented on samplers/aws/xray/proxy.go
> +		Transport: &http.Transport{Proxy: http.ProxyURL(proxyURL)},
I'm not sure it is a good idea for an SDK to have a hard dependency on the existence of a collector.  How can this be made to work without a collector in the environment?

2021-12-06 21:32 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +		t.Reset()
Use a [`time.Ticker`](https://pkg.go.dev/time#Ticker) instead.

2021-12-07 18:31 UTC, bhautikpip commented on samplers/aws/xray/proxy.go
> +		Transport: &http.Transport{Proxy: http.ProxyURL(proxyURL)},
No I don't think it's a hard dependency. For some reason if collector is not running then the call to collector would return bad response/no response so such cases would be handled by SDK as a fallback (for example as a fallback this implementation would use  1 req/sec reservoir and then 5% of fixed rate). The collector running would be the hard requirement when customer wants to use centralized sampling (from their custom set rules) because then how would we get customer's config, via collector only right?

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/client.go
> +		Transport: &http.Transport{Proxy: http.ProxyURL(proxyURL)},
This isn't actually an HTTP tunneling proxy, is it?  The extension in the collector is using [`httputil.ReverseProxy`](https://pkg.go.dev/net/http/httputil@go1.17.5#ReverseProxy), which is more like a façade in this case, and thus should just have a `POST` request directed at it, not a `CONNECT` request.

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/client.go
> +	req, err := http.NewRequestWithContext(ctx, http.MethodPost, p.proxyEndpoint+"/GetSamplingRules", nil)
Is this supposed to be a `POST` with no body?  That feels very wrong.

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/client.go
> +	_, _ = buf.ReadFrom(output.Body)
Don't skip error checking.

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/client.go
> +	_ = json.Unmarshal(buf.Bytes(), &samplingRulesOutput)
Don't skip error checking.

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +		return nil
This should return an error, the returned value is not usable and the caller should be informed why.

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/timer.go
> +func NewTicker(d, jitter time.Duration) *Ticker {
This doesn't need to be exported, does it?

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/timer.go
> +type Ticker struct {
This doesn't need to be exported, does it?

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +		t.Reset()
I still don't think it is necessary to reset the ticker every iteration.  Adding the jitter once at the beginning will be enough to spread out the requests from multiple consumers.

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +		rs.start()
This needs to be resolved before a PR is made upstream.  As it is, this can't really even be tested as it will lock the system the first time a sampling decision is required.

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +	actives := map[*centralizedRule]bool{}
I don't see anything there using a pointer type as a key into a map.  I see pointer types as values and struct types as keys.  The concern is that there might be multiple copies of a rule with identical data that have different addresses and thus are duplicated in the map.

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +		}
This constraint requires explanation.  There should be a README that describes exactly what rules this sampler can work with.  I think I would find it very confusing as a customer if the sampling rule definition allowed me to specify attributes but doing so resulted in an error and my rule not being used.

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +		}
This constraint requires explanation.  Ensure that the README details what rules are applicable to this sampler.

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/rule_manifest.go
> +	name := *rule.RuleName
```suggestion
	name := rule.RuleName
```

The dereference isn't necessary here, is it?

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/sampling_rule.go
> +	Version       *int64             `json:"Version"`
why are these all pointers instead of values?

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/rule_manifest.go
> +}
This should be a method on `*centralizedRule` and not `*centralizedManifest`.

```go
rule.update(properties)
```

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/rule_manifest.go
> +		return d
Should this rule be updated with the new properties?  If not, should an error be returned so that the caller can know that what whey requested be done was not done?

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/rule_manifest.go
> +}
Again, this should be `rule.update(properties)`.  It'd be the same implementation, just applied to a different rule.

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/rule_manifest.go
> +	r, ok := m.index[name]
Does this shadow `r`?  To be safe should this instead be:

```suggestion
	var ok bool
	r, ok = m.index[name]
```

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/rule_manifest.go
> +			m.rules[len(m.rules)-1] = nil
Is this necessary? Is it safe?  It seems like it might not be either.

2021-12-13 23:55 UTC, Aneurysm9 commented on samplers/aws/xray/rule_manifest.go
> +		if m.rules[i].ruleProperties.Priority == m.rules[j].ruleProperties.Priority {
I don't think this is doing what you think it is doing since all the values of `ruleProperties` are pointers.

2021-12-14 00:29 UTC, bhautikpip commented on samplers/aws/xray/client.go
> +	req, err := http.NewRequestWithContext(ctx, http.MethodPost, p.proxyEndpoint+"/GetSamplingRules", nil)
Yes, The getSamplingRules call has a not required body: https://docs.aws.amazon.com/xray/latest/api/API_GetSamplingRules.html

2021-12-14 01:01 UTC, bhautikpip commented on samplers/aws/xray/remote_sampler.go
> +		}
I will make sure to add these constraints in the README. I will add a README in the last PR of this implementation as README right now would be out of the scope of this PR. Also, it would be easier to write README once implementation is done as the last step of it.

2021-12-14 01:05 UTC, bhautikpip commented on samplers/aws/xray/sampling_rule.go
> +	Version       *int64             `json:"Version"`
The main reason being we can do `nil` checking and see if values are returned by the API. For example, some customer set `FixedRate` as 0 then we would not know if 0 is set because of the struct init or we are getting actual value from API. Just wanted to get the exact returned data from the API.

2021-12-14 01:18 UTC, bhautikpip commented on samplers/aws/xray/rule_manifest.go
> +		return d
No. This is like a sanity check if rule is already present in the rule cache then we do not create it. I don't think we need to return something to the caller here.

2021-12-17 00:59 UTC, Aneurysm9 commented on samplers/aws/xray/client.go
> +		return nil, err
```suggestion
		return nil, fmt.Errorf("xray client: unable to retrieve sampling settings: %w", err)
```

Errors should be wrapped and augmented with contextual information so that the caller can know where things went wrong.

2021-12-17 00:59 UTC, Aneurysm9 commented on samplers/aws/xray/client.go
> +		return nil, err
```suggestion
		return nil, fmt.Errorf("xray client: unable to read response body: %w", err)
```

2021-12-17 00:59 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +		return nil
```suggestion
		return fmt.Errorf("unable to generate client ID: %w", err)
```

Libraries generally shouldn't log errors, but return them to the caller who can decide what to do with them.

2021-12-17 00:59 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +		xrayClient: newClient("127.0.0.1:2000"),
This seems likely to require a change to the interface of this function to take options.  That should probably be done up-front to avoid breaking changes that can be foreseen.

2021-12-17 00:59 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +			log.Println("Successfully fetched sampling rules")
Logging to STDOUT within a library without user interaction can be very confusing to users and in some situations can break users' applications.  We should not do this.

2021-12-17 00:59 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +			if err := rs.refreshManifest(); err != nil {
```suggestion
		for {
			if err := rs.refreshManifest(); err != nil {
			...
			}
			select {
			case _, more := <-t.C:
			  if !more {
			    break
			  }
			  continue
			}
		}
```

The two goroutines started here could be collapsed into one by rearranging the block on the channel read.

Since this eventually makes a network request there should probably also be a `context.Context` wired through this and the `select` should have a `case <-ctx.Done()`.

2021-12-17 00:59 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +	rules, err := rs.xrayClient.getSamplingRules(context.Background())
This should be provided a context as a method argument and not create a new background context this deep in the call stack.

2021-12-17 00:59 UTC, Aneurysm9 commented on samplers/aws/xray/rule_manifest.go
> +	if *rule.RuleName == defaultRule {
I'm still not sure I understand why the default rule needs to be stored and processed separately.  It looks like it is handled in the same way as any other rule but has a special name.  A lot of duplicated logic here can be eliminated by deferring the handling of the difference until inside of `createRule()`.

2021-12-17 00:59 UTC, Aneurysm9 commented on samplers/aws/xray/sampling_rule.go
> +	Version       *int64             `json:"Version"`
Does the implementation ever do anything with that information?  I don't recall seeing it anywhere.  If it isn't used it would be easier to understand without this indirection.

2021-12-20 20:35 UTC, Aneurysm9 commented on samplers/aws/xray/client.go
> +		globalLogger.Printf("failed to create http request, %v\n", err)
Should this return at this point?  I don't think attempting to execute the request makes sense if there was an error creating it.

2021-12-20 20:35 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +	options := new(samplerOptions).applyOptionsAndDefaults(opts...)
```suggestion
func NewRemoteSampler(ctx context.Context, opts ...Option) (*RemoteSampler, error) {
	cfg := newConfig(opts)
```

See [the style guide](https://github.com/open-telemetry/opentelemetry-go/blob/main/CONTRIBUTING.md#configuration) for details on how the configuration types and functions should be named for consistency.

2021-12-20 20:35 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +	globalLogger = options.logger
It would probably be best to plumb the logger through if one is provided, using the global as a default.  Changing the global logger here can have side effects and complicate any attempt to have different loggers used by different samplers.

2021-12-20 20:35 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +	remoteSampler.mu.Unlock()
```suggestion
	remoteSampler.start(ctx)
```

The `remoteSampler` was just created with the `pollerStart` value initialized to `false`, so we know this will always be executed.  `remoteSampler.start()` also checks the `pollerStart` value itself, so this check is redundant and can be removed.

2021-12-20 20:35 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +	rs.pollerStart = true
```suggestion
	if !rs.pollerStart {
		rs.pollerStart = true
		rs.startRulePoller(ctx)
	}
```

2021-12-20 20:35 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +
```suggestion
```

This isn't needed, it'll be done first thing in the loop that follows.

2021-12-20 20:35 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +					break
```suggestion
					return
```

This is clearer and will survive more potential changes.

2021-12-20 20:35 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler.go
> +				break
```suggestion
				return
```

This is clearer and will survive more potential changes.

2021-12-20 20:35 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler_options.go
> +type samplerOptions struct {
```suggestion
type Option func(options *config)

type config struct {
```

This would be more in line with the [expected style](https://github.com/open-telemetry/opentelemetry-go/blob/main/CONTRIBUTING.md#configuration).

2021-12-20 20:35 UTC, Aneurysm9 commented on samplers/aws/xray/remote_sampler_options.go
> +}
```suggestion
func newConfig(opts ...Option) *config {
	cfg := &config{
		proxyEndpoint: defaultProxyEndpoint,
		samplingRulesPollingInterval: defaultPollingInterval * time.Second,
		logger: noopLogger{}
	}
	
	for _, option := range opts {
		option(cfg)
	}

	return cfg
}
```

By creating the `config` with the default values in place and then applying the provided options the function becomes simpler.

2021-12-21 00:11 UTC, merged